"""Per-arm sign convention for rolling motion.

The 12 joints are grouped by which physical arm they belong to:
    Arm A = front-left   (x=+, y=+ in the URDF)
    Arm B = front-right  (x=+, y=- in the URDF)
    Arm C = back-left    (x=-, y=+ in the URDF)
    Arm D = back-right   (x=-, y=- in the URDF)

Each arm's hip joint (A0/B0/C0/D0) was generated by Fusion2urdf with its
own local <axis>, and inspecting the xacro shows they are NOT all the same
sign (A0 and D0 use axis z=-1, B0 and C0 use axis z=+1). That means sending
the exact same angular velocity to all 12 joints does NOT necessarily spin
every arm the same physical direction.

FORWARD_SIGN below is the knob to fix that. It does not try to guess the
right values from the URDF alone (axis direction in a child link's local
frame can still be flipped again by the parent's <origin rpy>, so the only
fully reliable way to get this right is to look at the real robot/sim).

HOW TO CALIBRATE (do this once, in Gazebo):
  1. ros2 run gelinder_control transform_to_roll
  2. ros2 run gelinder_control roll_forward
  3. Watch the robot in Gazebo:
       - If it rolls/spins cleanly forward -> you're done, no changes needed.
       - If some arm visibly fights the others (e.g. spins backwards while
         the rest spin forward), flip that arm's sign below from +1 to -1
         (or vice versa) and try again.
  4. Once roll_forward looks right, roll_left/roll_right (which reduce one
     side's speed) will automatically inherit the corrected signs.
"""

FORWARD_SIGN = {
    "A": +1.0,
    "B": +1.0,
    "C": +1.0,
    "D": +1.0,
}

# Which joints belong to which arm, and which side of the robot the arm is
# on (left/right), used by roll_left / roll_right to slow down one side
# like a differential drive.
ARM_JOINTS = {
    "A": ["A0", "A1", "A2"],
    "B": ["B0", "B1", "B2"],
    "C": ["C0", "C1", "C2"],
    "D": ["D0", "D1", "D2"],
}

ARM_SIDE = {
    "A": "left",   # front-left
    "B": "right",  # front-right
    "C": "left",   # back-left
    "D": "right",  # back-right
}

# Order matches the `joints:` list in config/gelinder_controllers.yaml --
# gelinder_velocity_controller's ~/commands topic expects velocities in
# exactly this order.
JOINT_ORDER = [
    "A0", "A1", "A2",
    "B0", "B1", "B2",
    "C0", "C1", "C2",
    "D0", "D1", "D2",
]


def joint_arm(joint_name):
    """Return the arm letter ('A'..'D') a joint belongs to, e.g. 'B1' -> 'B'."""
    return joint_name[0]


def build_velocity_command(base_speed, left_scale=1.0, right_scale=1.0):
    """Build a list of 12 velocities (rad/s), in JOINT_ORDER, for a given
    base speed and per-side scale factor.

    base_speed: overall wheel spin speed in rad/s (positive = forward).
    left_scale / right_scale: multiplier applied to the left-side arms
        (A, C) and right-side arms (B, D) respectively. Use this to turn:
        e.g. left_scale=0.4, right_scale=1.0 makes the robot curve left
        while still moving forward (right side spins faster than left).
    """
    velocities = []
    for joint in JOINT_ORDER:
        arm = joint_arm(joint)
        side_scale = left_scale if ARM_SIDE[arm] == "left" else right_scale
        velocities.append(base_speed * FORWARD_SIGN[arm] * side_scale)
    return velocities
